# BuildSpec for deploying latest image to Amazon ECR
version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /myapp/AWS_ACCOUNT_ID
    AWS_DEFAULT_REGION: /myapp/AWS_DEFAULT_REGION
    IMAGE_REPO_NAME: /myapp/IMAGE_REPO_NAME
    #append date time in seconds to the image tag
    IMAGE_TAG: $CODEBUILD_RESOLVED_SOURCE_VERSION
    IMAGE_TAG: /myapp/IMAGE_TAG

phases:
  pre_build:
    commands:
      # Install the latest version of the AWS CLI
      - apt-get update
      - apt-get install -y awscli
      # Export AWS_ACCOUNT_ID
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      # Authenticate Docker with Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # Log in to Amazon ECR
      - echo Logging in to Amazon ECR...
  build:
    commands:
      # Build the Docker image
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # Tag the Docker image
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
# Environment variables are retrieved from AWS Systems Manager Parameter Store
# Environment variables are defined in the 'env' section at the top of the buildspec
# They can be set in the build project settings or passed during the build process
# Artifacts section (empty for this case)
artifacts:
  files:
    # No artifacts to be saved

# Environment variables are defined in the 'env' section at the top of the buildspec
# They can be set in the build project settings or passed during the build process
